"""
regen_paper_tables.py -- regenerate the manuscript's result tables at n=10.

The .tex still carries 3-seed (and 8-seed) numbers. This rebuilds each table from
the current CSVs in the paper's own LaTeX format, so the update is a paste rather
than a transcription. Every table gains the pre-adaptation reference row where a
retention column exists (see scripts/pre_adaptation_reference.py) -- without it a
retention number cannot be read as preservation.

Writes paper/tables_v2.tex. Reads only; changes no result file.
"""
from __future__ import annotations
import os
import numpy as np
import pandas as pd

R = "Data/results/"
OUT = "paper/tables_v2.tex"
REF_EV = 0.547884          # pre-adaptation source retention, EV
REF_PV = 0.612634          # pre-adaptation source retention, PV


def pm(mean, std, dec=2):
    """Paper's format: $0.53\\pm.02$ (leading zero dropped on the std)."""
    if not np.isfinite(mean):
        return "--"
    s = f"{std:.{dec}f}".lstrip("0") if np.isfinite(std) else ""
    return f"${mean:.{dec}f}\\pm{s}$"


def agg(df, by, col, dec=2):
    g = df.groupby(by)[col].agg(["mean", "std", "count"])
    return {k: (pm(v["mean"], v["std"], dec), int(v["count"])) for k, v in g.iterrows()}


def table_rq1():
    d = pd.read_csv(R + "rq1_coldstart.csv")
    Ns = [1, 7, 30, 60, 90]
    n = d.seed.nunique()
    L = [r"\begin{table}[t]", r"\centering",
         rf"\caption{{RQ1 target $\nrmse$ (mean$\pm$std, {n} seeds).}}",
         r"\label{tab:rq1}", r"\begin{tabular}{lccccc}", r"\toprule",
         r"$N$ (days) & " + " & ".join(str(x) for x in Ns) + r"\\", r"\midrule"]
    for b, lab in [("B0", "B0 (scratch)  "), ("B3", "B3 (warm)     "),
                   ("B4", "B4 (warm+EWC) ")]:
        cells = []
        for N in Ns:
            s = d[(d.baseline == b) & (d.n_days == N)].target_nrmse
            cells.append(pm(s.mean(), s.std()) if len(s) else "--")
        L.append(f"{lab} & " + " & ".join(cells) + r"\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return L


def two_axis(csv, group, label, caption, ref, order=None, dec=2):
    """Target + retention table with the pre-adaptation reference row."""
    d = pd.read_csv(csv)
    d = d[d.n_days == 30] if "n_days" in d.columns else d
    n = d.seed.nunique()
    t = agg(d, group, "target_nrmse", dec)
    r = agg(d, group, "source_retention_nrmse", dec)
    keys = order or sorted(t)
    L = [r"\begin{table}[t]", r"\centering",
         rf"\caption{{{caption} ($N{{=}}30$, \textbf{{{n} seeds}}). "
         r"The reference row is the transferred model \emph{before} any target "
         r"fine-tuning: a condition scoring below it has improved on the source, "
         r"not preserved it.}",
         rf"\label{{{label}}}", r"\begin{tabular}{lcc}", r"\toprule",
         r"Method & target $\nrmse$ & retention $\nrmse$\\", r"\midrule",
         rf"\emph{{before adaptation}} & -- & $\mathit{{{ref:.2f}}}$\\", r"\midrule"]
    for k in keys:
        if k not in t:
            continue
        name = str(k).replace("_", r"\_")          # LaTeX-safe outside math mode
        L.append(f"{name} & {t[k][0]} & {r.get(k, ('--',0))[0]}" + r"\\")
    L += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return L


def main():
    L = [r"% Regenerated by scripts/regen_paper_tables.py -- do not hand-edit.",
         r"% Replaces tab:rq1, tab:rq2, tab:bench, tab:clsuite, tab:pv.", ""]
    L += table_rq1()
    L += two_axis(R + "rq2_rq3_source.csv", "baseline", "tab:rq2",
                  "RQ2/RQ3", REF_EV, order=["B0", "B1", "B3", "B4", "B5"])
    L += two_axis(R + "ewc_bench.csv", "notes", "tab:bench",
                  "EWC-variant bench", REF_EV,
                  order=["B3_warm", "B5_replay", "V1_empFisher_l1",
                         "V1_empFisher_l10", "V1_empFisher_l100",
                         "V2_perlayer_l1", "V2_perlayer_l10", "V2_perlayer_l100",
                         "V3_hybrid"])
    L += two_axis(R + "cl_methods_bench.csv", "baseline", "tab:clsuite",
                  "Full CL suite (EV)", REF_EV,
                  order=["B3", "B5", "AGEM", "DERpp", "LwF", "MAS"])
    L += two_axis(R + "pv_rq2_rq3_source.csv", "baseline", "tab:pv",
                  "PV RQ2/RQ3", REF_PV, order=["B0", "B1", "B3", "B4", "B5"])

    os.makedirs("paper", exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(L))
    print("\n".join(L))
    print(f"\n[tables] wrote {OUT}")


if __name__ == "__main__":
    main()
